-- Migration 061 (0.20.0): proactive insight cards.
--
-- Daily-generated "noticed this" cards surfaced on the dashboard.
-- Each card stitches together a signal that already exists in the
-- system (anomaly, budget overrun trend, goal pace slip, unusual
-- recurring charge) with a one-line "why" and an optional action
-- the user can click.
--
-- Lifecycle:
--   • Generated by a scheduled scan (insights-scheduler) at most
--     once per day per tenant. The scanner dedupes against existing
--     open cards (same kind + same source_id) so we don't pile up
--     duplicates on consecutive runs.
--   • User can dismiss (permanent) or snooze (until a date).
--   • Cards older than 30 days auto-purge on the next scan to keep
--     the table small.
--
-- kind enum captures the signal category; source_kind+source_id
-- carry the polymorphic backref to the row that triggered the
-- card (anomaly_alerts.id, savings_goals.id, etc.) so the UI can
-- link through.

CREATE TABLE insight_cards (
  id            UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id     UUID        NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  kind          TEXT        NOT NULL,
  severity      TEXT        NOT NULL DEFAULT 'info',
  title         TEXT        NOT NULL,
  body          TEXT        NOT NULL,
  action_label  TEXT        NULL,
  action_url    TEXT        NULL,
  source_kind   TEXT        NULL,
  source_id     UUID        NULL,
  dismissed_at  TIMESTAMPTZ NULL,
  snoozed_until DATE        NULL,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT insight_cards_kind_check CHECK (kind IN (
    'anomaly',
    'budget_overrun_trend',
    'goal_pace_slipping',
    'unusual_recurring_charge',
    'cash_flow_warning',
    'fee_drag'
  )),
  CONSTRAINT insight_cards_severity_check CHECK (severity IN (
    'info', 'warn', 'critical'
  ))
);

-- "Open cards for this tenant" is the primary read pattern.
CREATE INDEX idx_insight_cards_tenant_open
  ON insight_cards (tenant_id, created_at DESC)
  WHERE dismissed_at IS NULL;

-- Dedupe lookup: when the generator finds a signal it checks
-- whether a card for that exact (kind, source_id) is already open.
CREATE UNIQUE INDEX idx_insight_cards_open_source
  ON insight_cards (tenant_id, kind, source_id)
  WHERE dismissed_at IS NULL AND source_id IS NOT NULL;

COMMENT ON TABLE insight_cards IS
  '0.20.0 — proactive "noticed this" cards generated by the daily scanner from existing signals (anomalies, budget trends, goal pace, etc.). Surfaced on the dashboard.';
